<?php

/**
 * @file
 * Contains pos_code.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pos_code_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pos_code module.
    case 'help.page.pos_code':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Code related to Portfolio of Solutions of the Driver EU project') . '</p>';
      return $output;

    default:
  }
}
